name: UI Project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]    
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version        
      - name: "Run build-chain"
        id: build-chain
        uses: eamattos/generic-artifact@main
        with:
          definition-file: https://github.com/eamattos/generic-artifact/blob/main/.github/workflows/github-actions.yml
      - name: Install dependencies
        run: dotnet restore
      - name: Test with dotnet
        run: dotnet test --logger trx --results-directory "output-${{ matrix.dotnet-version }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}_${{ github.ref_name }}_${{ github.run_id }}
          path: output-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}        
      - run: echo "🍏 This job's status is ${{ job.status }}."      
